# Generated by Django 5.1.3 on 2026-10-08 04:24

import django.contrib.gis.db.models.fields
import django.contrib.gis.db.models.functions
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("water", "Water"),
                            ("camp", "Camp"),
                            ("bailout", "Bail-out"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="", max_length=2000)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "geom_m",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.gis.db.models.functions.Transform("geom", 5070),
                        output_field=django.contrib.gis.db.models.fields.PointField(
                            spatial_index=False, srid=5070
                        ),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["geom_m"], name="waypoint_geom_m_gist"
                    )
                ],
            },
        ),
    ]
