# Generated by Django 5.1.3 on 2026-10-08 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0007_trailroute"),
        ("planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("from_way", models.CharField(blank=True, default="", max_length=64)),
                ("trail_name", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PlanStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "campsite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_stops",
                        to="geodata.campsite",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="planning.tripplan",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="tripplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("osm_id__isnull", False),
                    models.Q(("from_way", ""), _negated=True),
                    _connector="OR",
                ),
                name="trip_plan_has_a_trail",
            ),
        ),
        migrations.AddConstraint(
            model_name="planstop",
            constraint=models.UniqueConstraint(
                fields=("plan", "campsite"), name="unique_plan_stop"
            ),
        ),
    ]
