# Generated by Django 5.1.3 on 2026-10-08 20:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0007_trailroute"),
        ("planning", "0002_trip_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="planstop",
            name="candidate_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="planstop",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="planstop",
            name="campsite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_stops",
                to="geodata.campsite",
            ),
        ),
        migrations.AddConstraint(
            model_name="planstop",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("campsite__isnull", False),
                    models.Q(("candidate_id", ""), _negated=True),
                    _connector="OR",
                ),
                name="plan_stop_is_a_campsite_or_candidate",
            ),
        ),
    ]
