# Generated by Django 5.1.3 on 2026-10-08 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0003_candidate_stops"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("from_way", models.CharField(blank=True, default="", max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("length_m", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_trails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("osm_id__isnull", False),
                            models.Q(("from_way", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="saved_trail_has_a_trail",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("osm_id__isnull", False)),
                        fields=("user", "osm_id"),
                        name="unique_saved_route",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("osm_id__isnull", True)),
                        fields=("user", "from_way"),
                        name="unique_saved_assembled_trail",
                    ),
                ],
            },
        ),
    ]
