# Generated by Django 5.1.3 on 2026-10-02 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geodata", "0007_trailroute"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampsiteFacts",
            fields=[
                (
                    "campsite",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="facts",
                        serialize=False,
                        to="geodata.campsite",
                    ),
                ),
                ("method_version", models.CharField(max_length=16)),
                ("computed_at", models.DateTimeField()),
                ("land_name", models.CharField(blank=True, max_length=255)),
                ("land_manager", models.CharField(blank=True, max_length=128)),
                ("land_designation", models.CharField(blank=True, max_length=128)),
                ("land_access", models.CharField(blank=True, max_length=16)),
                ("land_gap_status", models.CharField(blank=True, max_length=1)),
                ("land_source_id", models.CharField(blank=True, max_length=128)),
                ("water_name", models.CharField(blank=True, max_length=255)),
                ("water_distance_m", models.FloatField(blank=True, null=True)),
                ("water_feature_type", models.CharField(blank=True, max_length=16)),
                ("water_perennial", models.BooleanField(blank=True, null=True)),
                ("water_source_id", models.CharField(blank=True, max_length=128)),
                ("trail_name", models.CharField(blank=True, max_length=255)),
                ("trail_distance_m", models.FloatField(blank=True, null=True)),
                ("trail_kind", models.CharField(blank=True, max_length=8)),
                ("trail_source_id", models.CharField(blank=True, max_length=128)),
                ("elevation_m", models.FloatField(blank=True, null=True)),
                ("slope_deg", models.FloatField(blank=True, null=True)),
                ("slope_pct", models.FloatField(blank=True, null=True)),
                ("osm_tags", models.JSONField(blank=True, default=dict)),
                ("shelter_kind", models.CharField(blank=True, max_length=16)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("display_name_derived", models.BooleanField(default=False)),
                ("provenance", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "campsite facts",
            },
        ),
    ]
