# Generated by Django 5.1.3 on 2026-10-08 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichment", "0001_initial"),
        ("geodata", "0007_trailroute"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteFacts",
            fields=[
                (
                    "route",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="facts",
                        serialize=False,
                        to="geodata.trailroute",
                    ),
                ),
                ("computed_at", models.DateTimeField()),
                ("length_m", models.FloatField()),
                ("gain_m", models.FloatField(blank=True, null=True)),
                ("loss_m", models.FloatField(blank=True, null=True)),
                ("difficulty", models.CharField(blank=True, max_length=16)),
                ("shenandoah", models.FloatField(blank=True, null=True)),
                ("route_type", models.CharField(max_length=16)),
                ("route_type_estimated", models.BooleanField(default=True)),
                ("nearest_campsite_m", models.FloatField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["difficulty"], name="enrichment__difficu_57e282_idx"),
                    models.Index(fields=["route_type"], name="enrichment__route_t_8c0bf1_idx"),
                ],
            },
        ),
    ]
