# Generated by Django 5.1.3 on 2026-10-02 20:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                (
                    "analysis",
                    models.CharField(help_text="Analysis name, e.g. weather.", max_length=64),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Analysis version that computed this.", max_length=32
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        help_text="The (quantised) geometry analysed.", srid=4326
                    ),
                ),
                ("window_start", models.DateTimeField(blank=True, null=True)),
                ("window_end", models.DateTimeField(blank=True, null=True)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("value", models.JSONField(help_text="The computed answer.")),
                (
                    "provenance",
                    models.JSONField(
                        help_text="What was used, when, and with what parameters: source, request, response metadata, computed_at."
                    ),
                ),
                ("computed_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["analysis", "expires_at"], name="analysis_an_analysi_d1db1a_idx"
                    )
                ],
            },
        ),
    ]
