# Generated by Django 5.1.3 on 2026-09-17 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ridb", "Recreation.gov (RIDB)"),
                            ("osm", "OpenStreetMap"),
                            ("nhd", "USGS NHD"),
                            ("padus", "PAD-US"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="The source's own stable identifier. Upsert key.", max_length=128
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Untouched source payload, for backfilling fields later.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("designated", "Designated site"),
                            ("primitive", "Primitive / dispersed"),
                            ("lean_to", "Lean-to or shelter"),
                            ("group", "Group site"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "reservable",
                    models.BooleanField(
                        blank=True, help_text="Null when the source doesn't say.", null=True
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["site_type"], name="geodata_cam_site_ty_81ac48_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"), name="unique_campsite_source"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IngestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ridb", "Recreation.gov (RIDB)"),
                            ("osm", "OpenStreetMap"),
                            ("nhd", "USGS NHD"),
                            ("padus", "PAD-US"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Area-of-interest name from the region config.", max_length=64
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("record_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bbox, date range, filters, and anything else affecting the result.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["source", "region"], name="geodata_ing_source_2dd9e5_idx"),
                    models.Index(fields=["-started_at"], name="geodata_ing_started_a982a7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicLand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ridb", "Recreation.gov (RIDB)"),
                            ("osm", "OpenStreetMap"),
                            ("nhd", "USGS NHD"),
                            ("padus", "PAD-US"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="The source's own stable identifier. Upsert key.", max_length=128
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Untouched source payload, for backfilling fields later.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                (
                    "manager",
                    models.CharField(
                        blank=True,
                        help_text="Managing agency, e.g. USFS, NPS, BLM, NY DEC.",
                        max_length=128,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        help_text="e.g. National Forest, State Forest Preserve, Wilderness Area.",
                        max_length=128,
                    ),
                ),
                (
                    "public_access",
                    models.CharField(
                        choices=[
                            ("open", "Open access"),
                            ("restricted", "Restricted access"),
                            ("closed", "Closed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["public_access"], name="geodata_pub_public__64afd6_idx"),
                    models.Index(fields=["manager"], name="geodata_pub_manager_13820d_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"), name="unique_publicland_source"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Trail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ridb", "Recreation.gov (RIDB)"),
                            ("osm", "OpenStreetMap"),
                            ("nhd", "USGS NHD"),
                            ("padus", "PAD-US"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="The source's own stable identifier. Upsert key.", max_length=128
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Untouched source payload, for backfilling fields later.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("geom", django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                (
                    "trail_type",
                    models.CharField(
                        blank=True,
                        help_text="Source classification, e.g. path, footway, track, bridleway.",
                        max_length=32,
                    ),
                ),
                ("length_m", models.FloatField(blank=True, null=True)),
                (
                    "osm_node_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered OSM node IDs. Shared nodes between ways are what make the routing graph possible in a later sprint - do not drop these.",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"), name="unique_trail_source"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WaterFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ridb", "Recreation.gov (RIDB)"),
                            ("osm", "OpenStreetMap"),
                            ("nhd", "USGS NHD"),
                            ("padus", "PAD-US"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="The source's own stable identifier. Upsert key.", max_length=128
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Untouched source payload, for backfilling fields later.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("stream", "Stream or river"),
                            ("lake", "Lake or pond"),
                            ("wetland", "Wetland"),
                            ("spring", "Spring"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "perennial",
                    models.BooleanField(
                        blank=True,
                        help_text="True if year-round, False if intermittent. Matters a lot for campsite water access - an intermittent stream is dry when you need it.",
                        null=True,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["feature_type"], name="geodata_wat_feature_8f5e9c_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"), name="unique_water_source"
                    )
                ],
            },
        ),
    ]
