# Generated by Django 5.1.3 on 2026-09-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campsite",
            name="last_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The ingest run that most recently created or updated this row. Gives per-row provenance; region is reachable through it as last_run__region.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_records",
                to="geodata.ingestrun",
            ),
        ),
        migrations.AddField(
            model_name="publicland",
            name="last_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The ingest run that most recently created or updated this row. Gives per-row provenance; region is reachable through it as last_run__region.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_records",
                to="geodata.ingestrun",
            ),
        ),
        migrations.AddField(
            model_name="trail",
            name="last_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The ingest run that most recently created or updated this row. Gives per-row provenance; region is reachable through it as last_run__region.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_records",
                to="geodata.ingestrun",
            ),
        ),
        migrations.AddField(
            model_name="waterfeature",
            name="last_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The ingest run that most recently created or updated this row. Gives per-row provenance; region is reachable through it as last_run__region.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_records",
                to="geodata.ingestrun",
            ),
        ),
    ]
