# Generated by Django 5.1.3 on 2026-09-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0002_campsite_last_run_publicland_last_run_trail_last_run_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicland",
            name="gap_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1 - Permanent protection, natural state"),
                    ("2", "2 - Permanent protection, some management"),
                    ("3", "3 - Permanent protection, extractive use allowed"),
                    ("4", "4 - No known protection mandate"),
                    ("", "Unknown"),
                ],
                default="",
                help_text="PAD-US GAP_Sts. Blank when the source did not say.",
                max_length=1,
            ),
        ),
        migrations.AddIndex(
            model_name="publicland",
            index=models.Index(fields=["gap_status"], name="geodata_pub_gap_sta_dfab7d_idx"),
        ),
    ]
