# Generated by Django 5.1.3 on 2026-10-02 20:11

import django.contrib.gis.db.models.fields
import django.contrib.gis.db.models.functions
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0005_prune_urban_trails"),
    ]

    operations = [
        migrations.AddField(
            model_name="campsite",
            name="geom_m",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.gis.db.models.functions.Transform("geom", 5070),
                output_field=django.contrib.gis.db.models.fields.PointField(
                    spatial_index=False, srid=5070
                ),
            ),
        ),
        migrations.AddField(
            model_name="trail",
            name="geom_m",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.gis.db.models.functions.Transform("geom", 5070),
                output_field=django.contrib.gis.db.models.fields.MultiLineStringField(
                    spatial_index=False, srid=5070
                ),
            ),
        ),
        migrations.AddField(
            model_name="waterfeature",
            name="geom_m",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.gis.db.models.functions.Transform("geom", 5070),
                output_field=django.contrib.gis.db.models.fields.GeometryField(
                    spatial_index=False, srid=5070
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="campsite",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["geom_m"], name="campsite_geom_m_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="trail",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["geom_m"], name="trail_geom_m_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="waterfeature",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["geom_m"], name="water_geom_m_gist"
            ),
        ),
    ]
