# Generated by Django 5.1.3 on 2026-10-02 20:36

import django.contrib.gis.db.models.fields
import django.contrib.gis.db.models.functions
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0006_metric_geometry"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ridb", "Recreation.gov (RIDB)"),
                            ("osm", "OpenStreetMap"),
                            ("nhd", "USGS NHD"),
                            ("padus", "PAD-US"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="The source's own stable identifier. Upsert key.", max_length=128
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Untouched source payload, for backfilling fields later.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("osm_id", models.BigIntegerField(db_index=True, help_text="OSM relation id.")),
                (
                    "ref",
                    models.CharField(
                        blank=True, help_text="Route reference, e.g. AT.", max_length=64
                    ),
                ),
                (
                    "network",
                    models.CharField(blank=True, help_text="e.g. lwn, rwn, nwn.", max_length=32),
                ),
                ("operator", models.CharField(blank=True, max_length=128)),
                (
                    "member_way_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="OSM way ids in relation order, every role included.",
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                (
                    "geom_m",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.gis.db.models.functions.Transform("geom", 5070),
                        output_field=django.contrib.gis.db.models.fields.MultiLineStringField(
                            spatial_index=False, srid=5070
                        ),
                    ),
                ),
                (
                    "length_m",
                    models.FloatField(
                        blank=True, help_text="Geodesic length of the main-line members.", null=True
                    ),
                ),
                (
                    "last_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ingest run that most recently created or updated this row. Gives per-row provenance; region is reachable through it as last_run__region.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_records",
                        to="geodata.ingestrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["geom_m"], name="route_geom_m_gist"
                    ),
                    models.Index(fields=["name"], name="geodata_tra_name_8438ca_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"), name="unique_route_source"
                    )
                ],
            },
        ),
    ]
